Hospital/Hospital/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from . import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls")),
    path('accounts/', include("accounts.urls"))

]+ static( settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Hospital/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("register/", views.register_user, name="register_user"),
    path("login/", views.login_user, name="login_user"),
    path("logout/", views.logout_user, name="logout_user"),
]

Hospital/main/urls.py
from django.urls import path
from . import views


app_name = "main"

urlpatterns = [

    path('', views.index_page, name="index_page"),
    path('contact/', views.contact_me, name="contact"),
    path('about/', views.about, name="about"),
    path('details/', views.details, name="details"),
    path('clinic/', views.clinic, name="clinic"),
    path('doctors/', views.doctors, name="doctors"),
    path("add/", views.add_clinic, name="addclinic"),
    

  
]

Hospital/accounts/models.py
from django.db import models

# Create your models here.

Hospital/main/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.


class Post(models.Model):

    title = models.CharField(max_length=1024)
    pcontent = models.TextField()
    release_date = models.DateField(auto_now_add=True)
    image = models.ImageField(upload_to="img/blog/", default="images/default.jpg")

    def __str__(self) -> str:
        return f"{self.title} "


class Appointment(models.Model):

    fullname =models.CharField(max_length=1024)
    email = models.EmailField()
    number = models.IntegerField()
    department = models.TextField()
    message = models.TextField()
    date = models.DateTimeField()





class Contact(models.Model):

    name = models.CharField(max_length=1024)
    email = models.EmailField()
    subject=models.CharField(max_length=500)
    content = models.TextField()




class Comment(models.Model):
    name = models.CharField(max_length=100)
    comment = models.CharField(max_length=1024)

Hospital/accounts/views.py
from django.shortcuts import render, redirect
from django.http import HttpRequest, HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
# Create your views here.

def register_user(request : HttpRequest):

    if request.method == "POST":
        new_user = User.objects.create_user(username=request.POST["username"], email=request.POST["email"], password=request.POST["password"], first_name = request.POST["first_name"], last_name = request.POST["last_name"])
        new_user.save()

        #if register successful redirect to sign in page
        return redirect("accounts:login_user")


    return render(request, "accounts/register.html")



def login_user(request : HttpRequest):

    loggin_msg = None
    
    if request.method == "POST":
        #authenticate user credentials
        user = authenticate(request, username= request.POST["username"], password = request.POST["password"] )

        if user is not None:
            #login user
            login(request, user)
            return redirect("main:index_page")
        else:
            loggin_msg = "Please Use correct Credentials"

    return render(request, "accounts/login.html", {"msg" : loggin_msg})



def logout_user(request : HttpRequest):

    logout(request)

    return redirect("main:index_page")

Hospital/main/views.py
from django.shortcuts import render , redirect
from django.http import HttpRequest, HttpResponse
from .models import Contact , Comment , Appointment
# Create your views here.


def index_page(request : HttpRequest):

 return render(request, "main/index.html")


def contact_me (request : HttpRequest):
      if request.method == "POST":
        new_contact = Contact(name= request.POST["name"], email = request.POST["email"],  content = request.POST["content"], subject = request.POST["subject"])
        new_contact.save()
        
        return redirect("main:contact")


      return render(request, "main/contact.html")

def about (request : HttpRequest):

    return render (request,"main/about.html")


def details (request : HttpRequest):
    comments=Comment.objects.all()
    if request.method == "POST":
        new_comment = Comment(name = request.POST["name"], comment= request.POST["comment"])
        new_comment.save()
        return redirect("main:details")
    return render (request,"main/details.html", {"comments":comments})
    

    return render (request,"main/details.html")


def clinic (request : HttpRequest):

    return render (request,"main/clinic.html")

def doctors (request : HttpRequest):

    return render (request,"main/doctors.html")


def add_clinic(request : HttpRequest):

    if not request.user.is_staff:
        return redirect("accounts:login_user")

    if request.method == "POST":
        #to add a new entry
        new_clinic = Post(title= request.POST["title"], pcontent = request.POST["pcontent"], release_date = request.POST["release_date"], image = request.FILES["img"])
        new_clinic.save()
        return redirect("main:clinic")


    return render(request,"main/addclinic.html")



def clinic_detail(request : HttpRequest, clinic_id):

    clinic = Post.objects.get(id=clinic_id)


    return render(request, "main/details.html", {"clinic" : clinic})

Hospital/accounts/templates/accounts/login.html
{% extends 'main/index.html' %}

{% block title %} Sign In {% endblock %}


{% block content %}

<div class="container">
    <h1>Sign In</h1>

    <form method="POST" action="">
        {% csrf_token %}
        <h2 class="h3 mb-3 fw-normal">Please sign in</h2>
        
        {% if msg %}
            <h6 class="text-danger" >{{msg}}</h6>
        {% endif %}
        <div class="form-floating mt-2">
            <input name="username" type="text" class="form-control"  placeholder="username">
            <label for="floatingInput">User Name</label>
          </div>


        <div class="form-floating mt-2">
          <input name="password" type="password" class="form-control" id="floatingPassword" placeholder="Password">
          <label for="floatingPassword">Password</label>
        </div>
    
        <button class="w-100 btn btn-lg btn-primary mt-2" type="submit">Log In</button>
        <p class="mt-5 mb-3 text-muted">© 2017-2022</p>
      </form>

      <h5>You don't have an account ? you can <a href="{% url 'accounts:register_user' %}">register</a></h5>

</div>

{% endblock %}

Hospital/accounts/templates/accounts/register.html
{% extends 'main/index.html' %}

{% block title %} Register New User {% endblock %}


{% block content %}

<div class="container">
    <h1>Register New user</h1>

    <form method="post" action="">
        {% csrf_token %}
        <h2 class="h3 mb-3 fw-normal">Please sign up / Register</h2>
    
        <div class="form-floating mt-2">
            <input name="username" type="text" class="form-control"  placeholder="username">
            <label for="floatingInput">User Name</label>
          </div>

        <div class="form-floating mt-2">
          <input name="email" type="email" class="form-control"  placeholder="name@example.com">
          <label for="floatingInput">Email address</label>
        </div>

        <div class="form-floating mt-2">
            <input name="first_name" type="text" class="form-control" id="floatingInput" placeholder="First Name">
            <label for="floatingInput">First Name</label>
        </div>


        <div class="form-floating mt-2">
            <input name="last_name" type="text" class="form-control" id="floatingInput" placeholder="username">
            <label for="floatingInput">Last Name</label>
        </div>

        <div class="form-floating mt-2">
          <input name="password" type="password" class="form-control" id="floatingPassword" placeholder="Password">
          <label for="floatingPassword">Password</label>
        </div>
    
        <button class="w-100 btn btn-lg btn-primary mt-2" type="submit">Register</button>
        <p class="mt-5 mb-3 text-muted">© 2017-2022</p>
      </form>

</div>


{% endblock %}

Hospital/main/templates/main/about.html
{% extends 'main/index.html' %}
{% load static %}
{% block content %}


  <div class="page-banner overlay-dark bg-image" style="background-image: url(../static/img/bg_image_1.jpg);">
    <div class="banner-section">
      <div class="container text-center wow fadeInUp">
        <nav aria-label="Breadcrumb">
          <ol class="breadcrumb breadcrumb-dark bg-transparent justify-content-center py-0 mb-2">
            <li class="breadcrumb-item"><a href="{% url 'main:index_page' %}">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">About</li>
          </ol>
        </nav>
        <h1 class="font-weight-normal">About Us</h1>
      </div> <!-- .container -->
    </div> <!-- .banner-section -->
  </div> <!-- .page-banner -->

  <div class="page-section bg-light">
    <div class="container">
      <div class="row">
        <div class="col-md-4 py-3 wow zoomIn">
          <div class="card-service">
            <div class="circle-shape bg-secondary text-white">
              <span class="mai-chatbubbles-outline"></span>
            </div>
            <p><span>Chat</span> with a doctors</p>
          </div>
        </div>
        <div class="col-md-4 py-3 wow zoomIn">
          <div class="card-service">
            <div class="circle-shape bg-primary text-white">
              <span class="mai-shield-checkmark"></span>
            </div>
            <p><span>One</span>-Health Protection</p>
          </div>
        </div>
        <div class="col-md-4 py-3 wow zoomIn">
          <div class="card-service">
            <div class="circle-shape bg-accent text-white">
              <span class="mai-basket"></span>
            </div>
            <p><span>One</span>-Health Pharmacy</p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="page-section">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-8 wow fadeInUp">
          <h1 class="text-center mb-3">Welcome to Your Health Center</h1>
          <div class="text-lg">
            <p>Established in 18th Feb 2023 One-Health medical intends to provide quality and affordable health care to our patients.Through One-Health, health awareness programme we have reached school children and spread oral health awareness, done check-ups and have run multiple campaigns for the prevention of medical and oral diseases.</p>
            <p>OUR CORE VALUES ARE <br> INTEGRITY, COMPASSION, COMMITMENT, TEAM WORK, PROFESSIONALISM
              These values are honoured in all we do for our patients, visitors, medical staff, associates, partners and volunteers
              At One-Health WE deliver care that is accessible, safe, appropriate, coordinated, effective and centred on the needs of each individual within a system that demonstrates continual improvement.
              We are here to learn and to serve, we have dedicated one special day for people who are needy and can not afford expensive Medical & Dental Treatment we Proudly call it FREE FRIDAYS every week on Fridays such patients are given free treatments .</p>
          </div>
        </div>
        <div class="col-lg-10 mt-5">
          <h1 class="text-center mb-5 wow fadeInUp">Our Doctors</h1>
          <div class="row justify-content-center">
            <div class="col-md-6 col-lg-4 wow zoomIn">
              <div class="card-doctor">
                <div class="header">
                  <img src="../static/img/doctors/doctor_1.jpg" alt="">
                  <div class="meta">
                    <a href="#"><span class="mai-call"></span></a>
                    <a href="#"><span class="mai-logo-whatsapp"></span></a>
                  </div>
                </div>
                <div class="body">
                  <p class="text-xl mb-0">Dr. Asma khalied </p>
                  <span class="text-sm text-grey">Cardiology</span>
                </div>
              </div>
            </div>
            <div class="col-md-6 col-lg-4 wow zoomIn">
              <div class="card-doctor">
                <div class="header">
                  <img src="../static/img/doctors/doctor_2.jpg" alt="">
                  <div class="meta">
                    <a href="#"><span class="mai-call"></span></a>
                    <a href="#"><span class="mai-logo-whatsapp"></span></a>
                  </div>
                </div>
                <div class="body">
                  <p class="text-xl mb-0">Dr. john Melvin</p>
                  <span class="text-sm text-grey">Dental</span>
                </div>
              </div>
            </div>
            <div class="col-md-6 col-lg-4 wow zoomIn">
              <div class="card-doctor">
                <div class="header">
                  <img src="../static/img/doctors/doctor_3.jpg" alt="">
                  <div class="meta">
                    <a href="#"><span class="mai-call"></span></a>
                    <a href="#"><span class="mai-logo-whatsapp"></span></a>
                  </div>
                </div>
                <div class="body">
                  <p class="text-xl mb-0">Dr. Rebecca Loran</p>
                  <span class="text-sm text-grey">General Health</span>
                </div>
              </div>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="page-section banner-home bg-image" style="background-image: url(../static/img/banner-pattern.svg);">
    <div class="container py-5 py-lg-0">
      <div class="row align-items-center">
        <div class="col-lg-4 wow zoomIn">
          <div class="img-banner d-none d-lg-block">
            <img src="../static/img/mobile_app.png" alt="">
          </div>
        </div>
        <div class="col-lg-8 wow fadeInRight">
          <h1 class="font-weight-normal mb-3">Get easy access of all features using One Health Application</h1>
          <a href="#"><img src="../static/img/google_play.svg" alt=""></a>
          <a href="#" class="ml-2"><img src="../static/img/app_store.svg" alt=""></a>
        </div>
      </div>
    </div>
  </div>

</body>

{% endblock %}

Hospital/main/templates/main/addclinic.html
{% extends 'main/index.html' %}

{% block title %} Add a New Post {% endblock %}

{% block content %}


<div class="container">
<h2>Add a New post</h2>

<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="mt-3">
      <label class="form-label">Title</label>
      <input type="text" name="title" class="form-control" />
    </div>

    <div class="mt-3">
      <label class="form-label">Description</label>
      <textarea class="form-control" name="pcontent"></textarea>
    </div>


    
      <div class="mt-3">
        <label class="form-label">Release Date</label>
        <input type="date" class="form-control" name="release_date"  />
      </div>

      <div class="mt-3">
        <label>Choose File:</label>
        <input type="file" name="img" class="form-control"/>
      </div>

      <br/>
      <input type="submit" class="btn btn-primary" value="New Game" />

    

</form>

</div>



{% endblock %}

Hospital/main/templates/main/contact.html
{% extends 'main/index.html' %}
{% load static %}

<body>
  {% block content %}


  <div class="page-banner overlay-dark bg-image" style="background-image: url(../static/img/bg_image_1.jpg);">
    <div class="banner-section">
      <div class="container text-center wow fadeInUp">
        <nav aria-label="Breadcrumb">
          <ol class="breadcrumb breadcrumb-dark bg-transparent justify-content-center py-0 mb-2">
            <li class="breadcrumb-item"><a href="index.html">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">Contact</li>
          </ol>
        </nav>
        <h1 class="font-weight-normal">Contact</h1>
      </div> <!-- .container -->
    </div> <!-- .banner-section -->
  </div> <!-- .page-banner -->

  <div class="page-section">
    <div class="container">
      <h1 class="text-center wow fadeInUp">Get in Touch</h1>

      <form method="POST" action ="" class="contact-form mt-5">
        {% csrf_token %}
        <div class="row mb-3">
          <div class="col-sm-6 py-2 wow fadeInLeft">
            <label for="fullName">Name</label>
            <input name="name" type="text" id="fullName" class="form-control" placeholder="Full name..">
          </div>
          <div class="col-sm-6 py-2 wow fadeInRight">
            <label for="emailAddress">Email</label>
            <input name="email" type="text" id="emailAddress" class="form-control" placeholder="Email address..">
          </div>
          <div class="col-12 py-2 wow fadeInUp">
            <label for="subject">Subject</label>
            <input name="subject" type="text" id="subject" class="form-control" placeholder="Enter subject..">
          </div>
          <div class="col-12 py-2 wow fadeInUp">
            <label for="message">Message</label>
            <textarea name="content" id="message" class="form-control" rows="8" placeholder="Enter Message.."></textarea>
          </div>
        </div>
        <button type="submit" class="btn btn-primary wow zoomIn">Send Message</button>
      </form>
    </div>
  </div>

  <div class="maps-container wow fadeInUp">
    <div id="google-maps"></div>
  </div>

  <div class="page-section banner-home bg-image" style="background-image: url(../static/img/banner-pattern.svg);">
    <div class="container py-5 py-lg-0">
      <div class="row align-items-center">
        <div class="col-lg-4 wow zoomIn">
          <div class="img-banner d-none d-lg-block">
            <img src="../static/img/mobile_app.png" alt="">
          </div>
        </div>
        <div class="col-lg-8 wow fadeInRight">
          <h1 class="font-weight-normal mb-3">Get easy access of all features using One Health Application</h1>
          <a href="#"><img src="../static/img/google_play.svg" alt=""></a>
          <a href="#" class="ml-2"><img src="../static/img/app_store.svg" alt=""></a>
        </div>
      </div>
    </div>
  </div> <!-- .banner-home -->
{% endblock %}
</body>

Hospital/main/templates/main/details.html
{% extends 'main/index.html' %}
{% load static %}

<body>
  {% block content %}


  <div class="page-section pt-5">
    <div class="container">
      <div class="row">
        <div class="col-lg-8">
          <nav aria-label="Breadcrumb">
            <ol class="breadcrumb bg-transparent py-0 mb-5">
              <li class="breadcrumb-item"><a href="index.html">Home</a></li>
              <li class="breadcrumb-item"><a href="blog.html">Blog</a></li>
              <li class="breadcrumb-item active" aria-current="page">List of Countries without Coronavirus case</li>
            </ol>
          </nav>
        </div>
      </div> <!-- .row -->

      <div class="row">
        <div class="col-lg-8">
          <article class="blog-details">
            <div class="post-thumb">
              <img src="../static/img/blog/blog_1.jpg" alt="">
            </div>
            <div class="post-meta">
              <div class="post-author">
                <span class="text-grey">By</span> <a href="#">Admin</a>  
              </div>
              <span class="divider">|</span>
              <div class="post-date">
                <a href="#">22 Jan, 2018</a>
              </div>
              <span class="divider">|</span>
              <div>
                <a href="#">StreetStyle</a>, <a href="#">Fashion</a>, <a href="#">Couple</a>  
              </div>
              <span class="divider">|</span>
              <div class="post-comment-count">
                <a href="#">8 Comments</a>
              </div>
            </div>
            <h2 class="post-title h1">List of Countries without Coronavirus case</h2>
            <div class="post-content">
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc sit amet est vel orci luctus sollicitudin. Duis eleifend vestibulum justo, varius semper lacus condimentum dictum. Donec pulvinar a magna ut malesuada. In posuere felis diam, vel sodales metus accumsan in. Duis viverra dui eu pharetra pellentesque. Donec a eros leo. Quisque sed ligula vitae lorem efficitur faucibus. Praesent sit amet imperdiet ante. Nulla id tellus auctor, dictum libero a, malesuada nisi. Nulla in porta nibh, id vestibulum ipsum. Praesent dapibus tempus erat quis aliquet. Donec ac purus id sapien condimentum feugiat.</p>

              <p>Praesent vel mi bibendum, finibus leo ac, condimentum arcu. Pellentesque sem ex, tristique sit amet suscipit in, mattis imperdiet enim. Integer tempus justo nec velit fringilla, eget eleifend neque blandit. Sed tempor magna sed congue auctor. Mauris eu turpis eget tortor ultricies elementum. Phasellus vel placerat orci, a venenatis justo. Phasellus faucibus venenatis nisl vitae vestibulum. Praesent id nibh arcu. Vivamus sagittis accumsan felis, quis vulputate</p>
            </div>
            <div class="post-tags">
              <a href="#" class="tag-link">LifeStyle</a>
              <a href="#" class="tag-link">Food</a>
              <a href="#" class="tag-link">Coronavirus</a>
            </div>
          </article> <!-- .blog-details -->

          <div class="comment-form-wrap pt-5">
            <h3 class="mb-5">Leave a comment</h3>
            <form action="" method="POST" class="">
              {% csrf_token %}
              <div class="form-row form-group">
                <div class="col-md-6">
                  <label for="name">Name *</label>
                  <input name='name' type="text" class="form-control" id="name">
                </div>
              </div>
              <div class="form-group">
                <label for="message">Message</label>
                <textarea name="comment" id="message" cols="30" rows="8" class="form-control"></textarea>
              </div>
              <div class="form-group">
                <input type="submit" href="{% url 'main:details'%}" value="Post Comment" class="btn btn-primary">
              </div>
  
            </form>
          </div>
        </div>
        <div class="col-lg-4">
          <div class="sidebar">
            <div class="sidebar-block">
              <h3 class="sidebar-title">Search</h3>
              <form action="#" class="search-form">
                <div class="form-group">
                  <input type="text" class="form-control" placeholder="Type a keyword and hit enter">
                  <button type="submit" class="btn"><span class="icon mai-search"></span></button>
                </div>
              </form>
            </div>

            <div class="sidebar-block">
              <h3 class="sidebar-title">Recent Blog</h3>
              <div class="blog-item">
                <a class="post-thumb" href="">
                  <img src="../static/img/blog/blog_1.jpg" alt="">
                </a>
                <div class="content">
                  <h5 class="post-title"><a href="#">{{ post.title }}</a></h5>
                  <div class="meta">
                    <a href="#"><span class="mai-calendar"></span>{{ post.release_date}}/a>
                    <a href="#"><span class="mai-person"></span> Admin</a>
                    <a href="#"><span class="mai-chatbubbles"></span> 19</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div> 
      </div> <!-- .row -->
    </div> <!-- .container -->
  </div> <!-- .page-section -->

  <div class="page-section banner-home bg-image" style="background-image: url(../static/img/banner-pattern.svg);">
    <div class="container py-5 py-lg-0">
      <div class="row align-items-center">
        <div class="col-lg-4 wow zoomIn">
          <div class="img-banner d-none d-lg-block">
            <img src="../static/img/mobile_app.png" alt="">
          </div>
        </div>
        <div class="col-lg-8 wow fadeInRight">
          <h1 class="font-weight-normal mb-3"> Get easy access of all features using One Health Application</h1>
          <a href="#"><img src="../static/img/google_play.svg" alt=""></a>
          <a href="#" class="ml-2"><img src="../static/img/app_store.svg" alt=""></a>
        </div>
      </div> <!-- .row -->
    </div> <!-- .container -->
  </div> <!-- .banner-home -->
  {% endblock %}
  
</body>